#version 460 core
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_ARB_bindless_texture : require

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(binding = 0, rgba16f) writeonly uniform image2D oindirect;
layout(binding = 1, rgba8) writeonly uniform image2D ospecular; 
layout(binding = 2, rgba16f) writeonly uniform image2D oemission;
layout(binding = 3, rgba16f) writeonly uniform image2D oindirectSpecular;
layout(binding = 4, rgba16f) writeonly uniform image2D oemissionSpecular;

#define INF 3.40282347e+38f

uniform sampler2D gPosition;
uniform sampler2D gNormal;
uniform sampler2D gAlbedoSpec;
uniform sampler2D depthMap;
uniform sampler2D gSpecular;
uniform sampler2D gEmission;
uniform highp sampler2D gVelocity;
uniform sampler2D swrtHDepth;
uniform float NearPlane;
uniform float FarPlane;

uniform mat4 u_ViewMatrix;
uniform mat4 u_ProjectionMatrix;
uniform vec3 cameraPosition;

uniform float time;
uniform int frame;

uniform vec3 directLightPos;
uniform vec3 directLightCol;
uniform bool doDirLight;
uniform float directAmbient;

uniform mat4 lightProjection;
uniform float dirSpecularLight;
uniform bool doDirSpecularLight;
uniform bool doReflect;
uniform sampler2D BlueNoiseHandle;
uniform samplerCube cmMainHandle;
uniform sampler2DShadow  shadowMap;
uniform int FilterRadius;
uniform int NumberOfSamples;
uniform float DirSMMaxBias;
uniform bool doDirShadowMap;

uniform vec3 sceneBoundPos;
uniform vec3 sceneBoundScale;

uniform bool doTemporalAccumulation;
uniform float temporalAccumulationBlendFactor;
uniform bool doDenoiseSplitDBGView;

uniform sampler2D hIndirect;
uniform sampler2D hEmission;
uniform sampler2D hIndirectSpecular;
uniform sampler2D hEmissionSpecular;
uniform sampler2D presentImage;

uniform vec2 screenSize;
// temp

struct localSDF{
    vec4 position;  // uv.x
    vec4 extents;  // uv.y
    vec4 rootPosition;
    vec4 rootExtents;
//vec4 gPosition;
//vec4 gExtents;
    mat4 globalTransform;

    uint64_t instanceUUID;
    sampler3D SDF_Handle;
    sampler3D ALB_Handle;
    uint64_t padding;
    //sampler2D texture_diffuse_Handle;
    //sampler2D texture_roughness_Handle;
    //sampler2D texture_normal_Handle;
    //sampler2D texture_emission_Handle;

};

layout(std430, binding = 11) buffer localSDF_Buffer {
    localSDF lSDFS[];
};


float mindist = 0.01f;

float r_maxdist = 15.0f;
int r_steps = 80;
int r_bounces =1;
int r_samples  = 1;
int r_minLodLevel = 2;
float r_noiseThreshold =1.0;
int r_coneSteps = 32;
float r_coneApature =0.1;
float r_coneKickInLevel = 0.5f; // .6 .7 are better settings
int r_ssrSteps = 256;
float r_ssrStepSize =0.5f;
bool r_doSSR = true;

float i_maxdist = 15.0f;
int i_steps = 80;
int i_samples = 1;
int i_minLodLevel = 5;
int e_minLodLevel = 7;
float i_noiseThreshold  = 1.0;
int i_coneSteps = 32;
float i_coneApature =0.1;

bool shadowsEnabled = true;
bool aosEnabled = false;
bool doContactShadows = true;
float ao_noiseThreshold =1.0;
bool doTextureAO = false;
//float maxshadowDistance = 0.0f;
//float ambientLight = 0.0;

bool drawSDFSCENE = false;
bool aabbHitDBGmode = false;

int maxlodLevel = 2;
float transitionRangeLOD = 10.0f;
//int SDFtextureLodLevel = 0;
float maxSDFDist = 512.0f;

float originEplison = 0.5f;

struct hitresult{
    vec3 normal;
    vec3 hitpos;
    vec2 uv;
    float distance;
    int materialIndex;
    bool isHit;
};


float sdBox(vec3 p, vec3 b){
    vec3 q = abs(p) - b;
    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0f);
}

vec3 rot3D(vec3 p, vec3 axis, float angle){
    return mix(dot(axis, p) * axis, p, cos(angle))
    + cross(axis, p * sin(angle));
}

float fOpUnionID(float res1, float res2){
    return (res1 < res2) ? res1 : res2;
}
vec4 fOpUnionID4(vec4 res1, vec4 res2){
    return (res1.x < res2.x) ? res1 : res2;
}

vec3 transformP(vec3 p, mat4 matrix){
    vec4 np = matrix * vec4(p, 1.0);
    return np.xyz;
}

float texture3DSDF(vec3 p, vec3 s, sampler3D handle, int lodLevel){
    vec3 distance = abs(p) - s;

    float outsideDistance = length(max(distance, 0.0));

    // map coords to 3d uv space
    vec3 uvw = (p / (s* 2.0)) + 0.5;

    float SDF = textureLod(handle, uvw, lodLevel).r;

    if (outsideDistance > 0.0) return SDF + outsideDistance;

    return SDF;
}

vec3 texture3DSDFUV(vec3 p, vec3 s, sampler3D handle, int lodLevel){
    vec3 distance = abs(p) - s;

    float outsideDistance = length(max(distance, 0.0));

    // map coords to 3d uv space
    vec3 uvw = (p / (s* 2.0)) + 0.5;

    vec3 SDF = textureLod(handle, uvw, lodLevel).rgb;

    if (outsideDistance > 0.0) return vec3(SDF.r + outsideDistance, SDF.yz);

    return SDF;
}

vec3 nearestPointOnAABB(vec3 p, vec3 pos, const vec3 extents){
    return clamp(p, pos - extents, pos + extents);
}

int calculateLODLevel(vec3 vPosition, vec3 cameraPosition, float transitionDistance, int maxLOD){
    float distance = distance(vPosition, cameraPosition);
    int targetLOD = int(distance / transitionDistance);
    targetLOD = min(targetLOD, maxLOD);

    return targetLOD;
}

vec4 SDFMesh(vec3 p, int index, int lodLevel){
    vec3 gp = transformP(p, lSDFS[index].globalTransform);
    vec3 fp = gp - lSDFS[index].position.xyz;

    vec3 nsdfv = texture3DSDFUV(fp, lSDFS[index].extents.rgb, lSDFS[index].SDF_Handle, lodLevel);

    vec2 uv = nsdfv.gb * vec2(lSDFS[index].position.w, lSDFS[index].extents.w);

    return vec4(nsdfv.r, float(index), uv);
}

float SDFMeshDist(vec3 p, int index, int lodLevel){
    vec3 gp = transformP(p, lSDFS[index].globalTransform);
    vec3 fp = gp - lSDFS[index].position.xyz;

    float nsdfv = texture3DSDFUV(fp, lSDFS[index].extents.rgb, lSDFS[index].SDF_Handle, lodLevel).r;

    return nsdfv;
}

vec4 sceneSDF(vec3 p ){ // scene
    vec4 tsdf = vec4(INF, 0.0, 0.0, 0.0);

    //aabbHitDBGmode

    if (sdBox(p - sceneBoundPos.xyz, sceneBoundScale.xyz) > tsdf.x) return tsdf;

    for (int i = 0; i < lSDFS.length(); i++ ){
        vec3 np = nearestPointOnAABB(cameraPosition, lSDFS[i].rootPosition.xyz, lSDFS[i].rootExtents.xyz);

        if (distance(np, cameraPosition) > maxSDFDist) continue;

        float root = sdBox(p - lSDFS[i].rootPosition.xyz, lSDFS[i].rootExtents.xyz);
        if (root < tsdf.x){

            if (aabbHitDBGmode){

                tsdf.x = root;
                continue;
            }

            int lodLevel = calculateLODLevel(np, cameraPosition, transitionRangeLOD, maxlodLevel);
            vec4 sdfm = SDFMesh(p, i, lodLevel);
            //vec4 sdfm = vec4(root, 0.0, 0.0, 0.0);

            if (i == 0) {
                tsdf = sdfm;
                continue;
            }
            tsdf = fOpUnionID4(tsdf,sdfm); //fOpUnionRoundID4 fOpUnionID4
        }
    }
    return vec4(tsdf);
}

float sceneSDFdist(vec3 p ){ // scene
    float tsdf = INF;

    if (sdBox(p - sceneBoundPos.xyz, sceneBoundScale.xyz) > tsdf.x) return tsdf;

    for (int i = 0; i < lSDFS.length(); i++ ){

        vec3 np = nearestPointOnAABB(cameraPosition, lSDFS[i].rootPosition.xyz, lSDFS[i].rootExtents.xyz);

        if (distance(np, cameraPosition) > maxSDFDist) continue;

        float root = sdBox(p - lSDFS[i].rootPosition.xyz, lSDFS[i].rootExtents.xyz);
        if (root < tsdf){

            if (aabbHitDBGmode){

                tsdf.x = root;
                continue;
            }

            int lodLevel = calculateLODLevel(np, cameraPosition, transitionRangeLOD, maxlodLevel);
            float sdfm = SDFMeshDist(p, i, lodLevel);

            if (i == 0) {
                tsdf = sdfm;
                continue;
            }
            tsdf = fOpUnionID(tsdf,sdfm); //fOpUnionRoundID4 fOpUnionID4

        }
    }
    return tsdf;
}

vec3 CalculateNormal( in vec3 p ){
    const float eps = 0.01;
    const vec2 h = vec2(eps,0);
    return normalize( vec3(sceneSDFdist(p+h.xyy) - sceneSDFdist(p-h.xyy),
            sceneSDFdist(p+h.yxy) - sceneSDFdist(p-h.yxy),
            sceneSDFdist(p+h.yyx) - sceneSDFdist(p-h.yyx) ) );
}

hitresult internalRayMarchScene(vec3 ro, vec3 rd, float maxdist, float mindist, int steps){
    hitresult hr;
    hr.isHit = false;

    float t = 0.0; // total distance travelled

    // raymarching
    for (int i = 0; i < steps; i++){
        vec3 pos = ro + rd* t;// position along the ray

        vec4 m = -sceneSDF(pos);
        float dist = m.x;

        t += dist;

        if (dist < mindist){ // treat as if hit
            hr.isHit = true;
            hr.distance = dist;
            hr.normal = CalculateNormal(pos);
            hr.materialIndex = int(m.y);
            hr.hitpos = pos;
            hr.uv = m.zw;

            break;// how small dist (radius around march)
        }
        if (dist > maxdist) break; // failed to hit
        //discard; // discard on far for transparency
        // how large dist (radius around march)
    }

    return hr;
}

hitresult raymarchScene(vec3 ro, vec3 rd, float maxdist, float mindist, int steps){
    hitresult hr;
    hr.isHit = false;
    float t = 0.0; // total distance travelled

    // raymarching
    for (int i = 0; i < steps; i++){
        vec3 pos = ro + rd* t;// position along the ray

        vec4 m = sceneSDF(pos);
        float dist = m.x;

        t += dist;

        if (dist < mindist){ // treat as if hit
            hr.isHit = true;
            hr.distance = dist;
            hr.normal = CalculateNormal(pos);
            hr.materialIndex = int(m.y);

            hr.hitpos = pos;
            hr.uv = m.zw;

            break;// how small dist (radius around march)
        }
        if (dist > maxdist) break; // failed to hit
        //discard; // discard on far for transparency
        // how large dist (radius around march)
    }

    return hr;
}

hitresult coneTraceScene(vec3 ro, vec3 rd, float maxdist, int steps, float aperture){
    hitresult hr;
    hr.isHit = false;
    float t = 0.0; // total distance travelled

    // raymarching
    for (int i = 0; i < steps; i++){
        vec3 pos = ro + rd* t;// position along the ray

        vec4 m = sceneSDF(pos);
        float dist = m.x;

        float radius = t * aperture;

        //radius += radius * aperture; // add by current radius * the aperture

        if (dist < radius){ // treat as if hit
            hr.isHit = true;
            hr.distance = dist;
            hr.normal = CalculateNormal(pos);
            hr.materialIndex = int(m.y);

            hr.hitpos = pos;
            hr.uv = m.zw;

            break;// how small dist (radius around march)
        }
        if (dist > maxdist) break; // failed to hit

        t += max(dist, radius);
    }

    return hr;
}

float CalcShadowFactorDIR(vec4 LightSpacePos, vec3 lightDirection, vec3 normal, vec3 iPosition, vec2 texCoord){
    // perform perspective divide
    vec3 lightCoords = LightSpacePos.xyz / LightSpacePos.w;
    float shadow = 0.0f;

    // shadow calculation
    if (lightCoords.z <= 1.0f){
        sampler2D bluemap =sampler2D(BlueNoiseHandle) ;
        lightCoords = (lightCoords + 1.0f) / 2.0f;
        // get the current depth
        float currentDepth = lightCoords.z;
        // calculate shadow bias
        float bias = max(DirSMMaxBias * (1.0f - dot(normal, lightDirection)), 0.0005f);
        // PCF
        int sampleRadius = FilterRadius; // FilterRadius // NumberOfSamples
        vec2 texSize = vec2(textureSize(bluemap, 0));
        // uv
        vec2 offset = vec2(fract(frame * 0.618), fract(frame * 0.133));
        vec2 noiseUV = (texCoord / texSize) + offset;

        vec2 pixelSize = 1.0 / textureSize(shadowMap, 0);
        float tsamples = 0.0;
        for(int y = -sampleRadius; y <= sampleRadius; y++){
            for(int x = -sampleRadius; x <= sampleRadius; x++){
                float angle = texture(bluemap, noiseUV).r * NumberOfSamples;
                vec2 foffset = vec2(cos(angle), sin(angle));
                float closestDepth = texture(shadowMap, vec3(lightCoords.xy + (vec2(x, y) * foffset) * pixelSize, currentDepth - bias )).r;
                //if (currentDepth > closestDepth + bias)
                shadow += (1.0f - closestDepth);
                tsamples += 1.0f;

            }
        }

        shadow /= tsamples;
    }

    return shadow;
}

vec4 RayCast(in vec3 dir, inout vec3 hitCoord, out float dDepth, int maxSteps, out float hit, in float step){
    hitCoord += dir * 0.1;
    //hitCoord += dir;

    dir *= step;
    float depth;
    vec4 projectedCoord = vec4(0.0);

    for (int i = 1; i < maxSteps; i++){
        hitCoord += dir;

        projectedCoord = u_ProjectionMatrix * vec4(hitCoord, 1.0);
        projectedCoord.xy /= projectedCoord.w;
        projectedCoord.xy = projectedCoord.xy * 0.5 + 0.5;

        if (projectedCoord.x < 0.0 || projectedCoord.x > 1.0 || projectedCoord.y < 0.0 || projectedCoord.y > 1.0) {
            break;
        }

        vec3 sampledWorldPos = textureLod(gPosition, projectedCoord.xy, 2).xyz;

        vec3 sampledViewPos = (u_ViewMatrix * vec4(sampledWorldPos, 1.0)).xyz;

        if (length(sampledWorldPos) < 0.001) {
            continue;
        }
        dDepth = hitCoord.z - sampledViewPos.z;


        if((dir.z - dDepth) < 0.3){
            if(dDepth <= 0.0){
                vec4 Result;
                Result = vec4(projectedCoord.xy, dDepth, 1.0);
                hit = 1.0;

                return Result;
            }
        }
    }
    hit = 0.0;
    return vec4(projectedCoord.xy, dDepth, 1.0);
}

float hash2(vec2 p) {
    p = fract(p * vec2(123.34, 456.21));
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

float shadowTrace(vec3 lightDirection, vec3 normal, vec3 iPosition, out bool ohit, vec2 texCoord){
    vec3 viewPos    = (u_ViewMatrix * vec4(iPosition, 1.0)).xyz;
    vec3 viewNormal = normalize(mat3(u_ViewMatrix) * normal);

    vec3 viewLightDir = normalize(mat3(u_ViewMatrix) * lightDirection);

    vec3 rayOrigin = viewPos + viewNormal * 0.1;


    vec2 uv = texCoord;
    float noiseX = hash2(uv + vec2(time));
    float noiseY = hash2(uv + vec2(time + 1.5));
    vec3 jitter = vec3(noiseX - 0.5, noiseY - 0.5, 0.0) * 0.03;

    vec3 rayDir = normalize(viewLightDir + jitter);

    float dDepth;
    float hit = 0.0;

    float shadow = 0.0f;
    ohit = false;

    //vec3 wp = vec3(vec4(viewPos, 1.0) * inverseViewMatrix);
    //vec3 t = vec3(time, time +2, time + 3);
    //vec3 jitt = mix(vec3(0.0), vec3(hash(wp + t)), 0.1); // time
    //jitt * time;

    //vec4 csCoords = RayCast((vec3(jitt)) + rayDir, rayOrigin, dDepth, 12, hit, 0.05);
    vec4 csCoords = RayCast(rayDir, rayOrigin, dDepth, 64, hit, 0.05);
    if (hit == 1.0f){
        shadow += 1.0f;
        ohit = true;
    }
    return shadow;
}


vec4 direcLight(vec3 ARM, vec3 iNormal, vec3 iPosition, bool isPrimary, vec2 texCoord){ // normals need to be recalculated based on rotation
    if (!shadowsEnabled) return vec4(1.0);
    // shadow map 
    float shadow = 0.0f;

    vec3 normal = normalize(iNormal);

    vec3 lightDirection = normalize(directLightPos); //vec3(1.0f, 1.0f, 0.0f)
    float diffuse = max(dot(normal, lightDirection), 0.0f);

    vec4 fragPosLight = lightProjection * vec4(iPosition, 1.0f);

    float smShadow = 0.0;
    //float rmShadow = 0.0f;
    float ssShadow = 0.0f;
    bool hit = false; // will be set to false inside ssshadow;

    //if (!hit) 
    if (isPrimary) ssShadow = shadowTrace(lightDirection, normal, iPosition, hit, texCoord);
    if (doDirShadowMap && !hit) smShadow = CalcShadowFactorDIR(fragPosLight, lightDirection, normal, iPosition, texCoord);
    //vec3 origin = iPosition + iNormal * originEplison;
    //if (!hit) rmShadow = 1.0 - softshadow(origin, normalize(directLightPos), minShadowDistance, maxshadowDistance, shadowSteps);
    //shadow = max(rmShadow ,max(smShadow, ssShadow)); // rmshadow is just way too dam slow
    shadow = max(smShadow, ssShadow);
    //shadow = smShadow;
    if (doTextureAO) shadow *= ARM.r;


    //float fAmbient = directAmbient * ARM.r;
    float specularFactor = 1.0;
    float specular = 0.0f;
    if (doReflect && doDirSpecularLight && diffuse != 0.0f){

        //return (vec4( vec3(1.0 , 0.0, 0.0), 1.0));

        vec3 reflectionDirection = reflect(-lightDirection, normal);
        vec3 viewDirection = normalize(cameraPosition - iPosition);
        vec3 halfwayVec = normalize(viewDirection + lightDirection);

        float specAmount = pow(max(dot(normal, halfwayVec), 0.0f), 16);
        //float specAmount = pow(max(dot(viewDirection, reflectionDirection), 0.0f), 16);
        specular = specAmount * dirSpecularLight;


        //   return ((diffuse * (1.0f - shadow)) + ARM.g* specular * (1.0f - shadow)) * vec4(directLightCol, 1.0f); }
        //else{ return ((diffuse * (1.0f - shadow))) * vec4(directLightCol, 1.0f); }

        return ((diffuse * (1.0f - shadow) + directAmbient) + specularFactor* specular * (1.0f - shadow)) * vec4(directLightCol, 1.0f); }
    else{ return ((diffuse * (1.0f - shadow) + directAmbient)) * vec4(directLightCol, 1.0f); }
}


//https://www.shadertoy.com/view/ttc3zr thank you for the hash function
uvec3 murmurHash33(uvec3 src) {
    const uint M = 0x5bd1e995u;
    uvec3 h = uvec3(1190494759u, 2147483647u, 3559788179u);
    src *= M; src ^= src>>24u; src *= M;
    h *= M; h ^= src.x; h *= M; h ^= src.y; h *= M; h ^= src.z;
    h ^= h>>13u; h *= M; h ^= h>>15u;
    return h;
}

// 3 outputs, 3 inputs
vec3 hash33(vec3 src) {
    uvec3 h = murmurHash33(floatBitsToUint(src));
    return uintBitsToFloat(h & 0x007fffffu | 0x3f800000u) - 1.0;
}

vec3 fresnelSchlick(float cosTheta, vec3 F0) { return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0); }

const float reflectionSpecularFalloffExponent = 3.0;

vec4 ssr(vec3 ARM, vec3 position, vec3 normal, int maxSteps, float step, sampler2D hColour, out vec3 gpos, out vec3 gNrm, vec2 texCoord){
    float Metallic = ARM.b;
    float rough = ARM.g;

    //bool fallback;

    if(Metallic < 0.01) return vec4(0.0);

    vec3 viewPos    = (u_ViewMatrix * vec4(position, 1.0)).xyz;
    vec3 viewNormal = mat3(u_ViewMatrix) * normal;

    vec3 V = normalize(viewPos);
    vec3 R = reflect(V, viewNormal);

    vec3 hitPos = viewPos;
    float dDepth;
    float hit = 0.0;

    //return vec4(V, 1.0);
    //return vec4(normalize(viewPos) * 0.5 + 0.5, 1.0);

    vec3 F0 = vec3(0.04);
    F0      = mix(F0, texture(gAlbedoSpec, texCoord.xy).rgb, Metallic);
    vec3 Fresnel = fresnelSchlick(max(dot(normalize(viewNormal), normalize(V)), 0.0), F0);


    vec3 wp = vec3(vec4(viewPos, 1.0) * u_ViewMatrix);
    vec3 t = vec3(time,time +1,time +3);
    //vec3 jitt = mix(vec3(0.0), vec3(hash31(rough)), rough); // time
    vec3 jitt = mix(vec3(0.0), vec3(hash33(wp + t)), rough); // time

    //vec4 csCoords = RayCast(R, hitPos, dDepth, 32);
    //vec4 csCoords = RayCast(R, hitPos, dDepth, 32, hit, 0.10);

    vec3 rayDir = normalize(R + jitt) * step;

    ivec2 size = ivec2(textureSize(gNormal, 0)); // get size of tex

    vec4 csCoords = RayCast(rayDir, hitPos, dDepth, maxSteps, hit, step);

    if (hit == 1.0)
    {
        //vec4 csCoords = RayCast(vec3(jitt) + R, hitPos, dDepth, maxSteps, hit, step);

        vec2 dCoords = smoothstep(0.2, 0.6, abs(vec2(0.5, 0.5) - csCoords.xy));
        //vec2 dCoords = smoothstep(0.2, 0.6, abs(vec2(0.5, 0.5) - texCoord.xy));

        float screenEdgefactor = clamp(1.0 - (dCoords.x + dCoords.y), 0.0, 1.0);

        float reflectionMultiplier = pow(Metallic, reflectionSpecularFalloffExponent) *
        screenEdgefactor *
        -R.z;

        vec3 SSR = textureLod(hColour, csCoords.xy, 0).rgb;//hColour
        //vec3 SSR = textureLod(hColour, csCoords.xy, 0).rgb * clamp(ReflectionMultiplier, 0.0, 0.9);//hColour
        gpos = texture(gPosition, csCoords.xy).rgb;
        gNrm = normalize(texture(gNormal, csCoords.xy).xyz);
        return vec4(clamp(SSR,0.0, 1.0), reflectionMultiplier);//Metallic
    }
    return vec4(0.0);
}


vec3 reflection(vec3 pArm, vec3 pNrm, vec3 ro, vec3 rd, float maxdist, float mindist, int steps, int bounces, int refSteps, bool doSSR, vec2 texCoord){
    vec3 colour = vec3(0.0); int hitcount = 0;

    vec3 F0 = vec3(0.04);
    F0      = mix(F0, texture(gAlbedoSpec, texCoord.xy).rgb, pArm.b);
    vec3 Fresnel = fresnelSchlick(max(dot(normalize(pNrm), normalize(normalize(rd))), 0.0), F0);

    //ssr
    vec3 gPos = vec3(0.0f);
    vec3 gNrm = vec3(0.0f);
    vec4 nSSR = vec4(0.0f);

    if (doSSR) nSSR = ssr(pArm, ro, pNrm, r_ssrSteps, r_ssrStepSize, presentImage, gPos, gNrm, texCoord);

    if (nSSR.a == 1.0f){
        ro = gPos;
        rd = gNrm;
        colour = nSSR.rgb;

        bounces -= 1;
    }

    if (bounces <= 0) return nSSR.rgb;

    for (int x = 0; x < refSteps; x++){
        vec3 lastorigin = ro;
        vec3 lastdir = rd;

        float rough = pArm.g;
        float met = pArm.b;

        float dim = 1.0f;
        vec3 wp = vec3(ro);
        vec3 t = vec3(time, time +1 + x, time +3 + x);
        vec3 jitt = mix(vec3(0.0), vec3(hash33(wp + t)), pArm.g);

        for (int i = 0; i < bounces; i++){
            if (dim <= 0.0f) break;
            hitcount++;

            hitresult hr;
            if (rough >= r_coneKickInLevel) hr = coneTraceScene(lastorigin, normalize(lastdir + jitt), maxdist, r_coneSteps, r_coneApature);
            else  hr = raymarchScene(lastorigin, normalize(lastdir + jitt), maxdist, mindist, steps); // raytraceRootHit raymarchScene

            if (hr.isHit){

                vec3 origin = hr.hitpos + hr.normal * originEplison;
                lastorigin = origin;

                vec3 F0 = vec3(0.04);
                F0      = mix(F0, texture(gAlbedoSpec, texCoord.xy).rgb, met);
                vec3 Fresnel = fresnelSchlick(max(dot(normalize(hr.normal), normalize(normalize(lastdir))), 0.0), F0);

                lastdir = reflect(lastdir, hr.normal); // probably looks very off cause the normal is smooth

                //material nMaterial = getMaterial(hr.materialIndex, hr.uv, clamp(i + r_minLodLevel, 0, 10));
                //vec3 ncolour = textureLod(lSDFS[hr.materialIndex].texture_diffuse_Handle, hr.uv, r_minLodLevel).rgb;
                //vec3 arm = textureLod( lSDFS[hr.materialIndex].texture_roughness_Handle, hr.uv, r_minLodLevel).rgb;

                vec3 ncolour = vec3(1.0);
                vec3 arm = vec3(1.0, 1.0, 0.0);
                
                rough = arm.g;
                met = arm.b;

                wp = vec3(hr.hitpos);
                t = vec3(time,time + i + x + 1,time + x + i + 3);
                jitt = mix(vec3(0.0), vec3(hash33(wp + t)), rough);

                vec3 shadow = direcLight(arm, hr.normal, hr.hitpos, false, texCoord).rgb;
                shadow += directAmbient;
                shadow = clamp(shadow, 0.0, 1.0);

                vec3 diffuseComponent = ncolour * shadow;

                colour += (diffuseComponent * dim) * Fresnel;
                dim *=  0.5f;
            }
            else {
                vec3 sky = texture(cmMainHandle, normalize(lastdir + jitt)).rgb;
                colour += (sky* dim) * Fresnel;
                //colour += skycolour * dim; 
                break;
            }
        }

    }
    vec3 fColour = clamp((colour/ hitcount), 0.0f, 1.0f);

    fColour = mix(fColour, nSSR.rgb, nSSR.a);

    return fColour;
}

float rand(vec2 co){
    return fract(sin(dot(co.xy ,vec2(12.9898, 78.233))) * 43758.5453);
}

vec3 sampleHemisphere(vec3 normal, int index, vec2 texCoord){
    float u = rand(texCoord + rand(vec2(time, float(index) ) ) );
    float v = rand(vec2(u, rand( vec2(time, float(index) ) ) ) );

    float phi = 2.0 * 3.14159265 * u;
    float cosTheta = sqrt(1.0 - v);
    float sinTheta = sqrt(v);

    vec3 localDir = vec3(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta);

    vec3 helper = abs(normal.y) < 0.999 ? vec3(0, 1, 0) : vec3(1, 0, 0);
    vec3 tangent = normalize(cross(helper, normal));
    vec3 bitangent = cross(normal, tangent);

    return tangent * localDir.x + bitangent * localDir.y + normal * localDir.z;
}

struct indirectChannels{
    vec3 specular; // this is here for accum
    vec4 indirect;
    vec4 emission;
    vec4 idirectSpecular;
    vec4 emissionSpecular;
};

indirectChannels indirectAndEmissionMarch(vec3 pArm, vec3 pNrm, vec3 ro, vec3 rd, float maxdist, float mindist, int steps, int samples, vec2 texCoord){
    vec3 indColour = vec3(0.0);
    vec3 emColour = vec3(0.0);

    int indHitCount = 0;
    int emHitCount = 0;
    vec3 lastNrm = pNrm;
    vec3 lastArm = pArm;
    //                lastdir = reflect(lastdir, hr.normal); 
    for (int i = 0; i < samples; i++){
        indHitCount++;

        vec3 newDir = sampleHemisphere(rd, i, texCoord);
        //newDir = mix(reflect(rd, pNrm), newDir, clamp(lastArm.g, 0.7, 1.0));
        //hitresult hr;
        //if (lastArm.g >= 0.6) hr = coneTraceScene(ro, newDir, maxdist, 32, 0.1);
        //else         hr = raymarchScene(ro, newDir, maxdist, mindist, steps);
        hitresult hr = raymarchScene(ro, newDir, maxdist, mindist, steps);
        //hitresult hr = coneTraceScene(ro, newDir, maxdist, i_coneSteps, i_coneApature);

        if (hr.isHit){
            //material nMaterial = getMaterial(hr.materialIndex, hr.uv, i_minLodLevel);
            emHitCount++;

            lastArm = vec3(1.0, 1.0, 0.0);
            vec3 mcolour = vec3(1.0);

            vec3 origin = hr.hitpos + hr.normal * originEplison;

            vec3 shadow = direcLight(lastArm, hr.normal, hr.hitpos, false, texCoord).rgb;
            shadow += directAmbient;
            shadow = clamp(shadow, 0.0, 1.0);

            vec3 diffuseComponent = mcolour * shadow;

            emColour += vec3(0.0);
            indColour += diffuseComponent;
        }
        else {
            vec3 sky = textureLod(cmMainHandle, newDir, 5).rgb;
            indColour += sky;
            break;
        }
        //colour = colour / hitcount;
        //colour = (colour)/ hitcount;
        // this is where we write cache
        //hr.uvw;
    }
    indirectChannels nIC;
    nIC.indirect.rgb = clamp(indColour / indHitCount, 0.0, 1.0);
    nIC.emission.rgb = clamp(emColour / emHitCount, 0.0, 1.0);
    return nIC;
}


float hash1( float n ){
    return fract(sin(n)*43758.5453123);
}

vec3 forwardSF( float i, float n ){
    const float PI  = 3.141592653589793238;
    const float PHI = 1.618033988749894848;
    float phi = 2.0*PI*fract(i/PHI);
    float zi = 1.0 - (2.0*i+1.0)/n;
    float sinTheta = sqrt( 1.0 - zi*zi);
    return vec3( cos(phi)*sinTheta, sin(phi)*sinTheta, zi);
}


float calcAO( in vec3 pos, in vec3 nor ){
    float ao = 0.0;
    for( int i=0; i<32; i++ ){
        vec3 ap = forwardSF( float(i), 32.0 );
        float h = hash1(float(i));
        ap *= sign( dot(ap,nor) ) * h*0.1;
        ao += clamp( sceneSDFdist( pos + nor*0.01 + ap )*3.0 , 0.0, 1.0 );
    }
    ao /= 32.0;

    return clamp( ao*6.0, 0.0, 1.0 );
}

float blueNoise(vec2 texCoord){ // for fade out or opacity (cheap) (could fade out near farplane or nearplane)
    vec2 texSize = vec2(textureSize(BlueNoiseHandle, 0));
    vec2 offset = vec2(fract(frame * 0.618), fract(frame * 0.133));
    vec2 noiseUV = (texCoord / texSize) + offset;

    return texture(BlueNoiseHandle, noiseUV).r;
}

bool discardThresholdFloat(float i, float t){
    if (i > t) return true;
    return false;
}

vec3 rayDirfromCam(mat4 projection, mat4 view, ivec2 pixelCoords, ivec2 size){
    // uv
    vec2 uv = (vec2(pixelCoords) + 0.5) / vec2(size) * 2.0 - 1.0;
    vec4 target = projection * vec4(uv.x, uv.y, -1.0, 1.0);
    vec3 rayDirView = normalize(target.xyz / target.w);
    vec3 rayDirWorld = normalize(mat3(view) * rayDirView);

    return normalize(rayDirWorld);
}

float lumaFromRGB(vec3 rgb){
    vec3 weights = vec3(0.2126, 0.7152, 0.0722);
    float luminance = dot(rgb, weights);
    return luminance;
}

float linearizeDepth(float depth, float NearPlane, float FarPlane){
    return (2.0 * NearPlane * FarPlane) / (FarPlane + NearPlane - (depth * 2.0 - 1.0) * (FarPlane - NearPlane));
}

vec4 accumulate(vec3 Input, sampler2D previous, highp vec2 historyTexCoord, float factor){
    vec4 previousColour = texelFetch(previous, ivec2(historyTexCoord), 0);
    /*
    float pLuma = lumaFromRGB(previousColour.rgb);
    float cLuma = lumaFromRGB(Input);
    float variance = abs(cLuma - pLuma);
    variance = clamp(variance, 0.0, 1.0);
    float cweight = mix(0.9, 0.0, variance);
    */

    vec3 accumulated = mix(Input, previousColour.rgb, factor);

    // calc variance
    float inputLuma = lumaFromRGB(Input);
    float accumLuma = lumaFromRGB(accumulated);
    float nvariance = (inputLuma - accumLuma) * (inputLuma - accumLuma);
    float accumVariance = mix(nvariance, previousColour.a, temporalAccumulationBlendFactor);

    return vec4(accumulated, accumVariance);
}

indirectChannels temporalAccumulate(indirectChannels Input, highp vec2 historyTexCoord, float currentDepth, float roughness){
    // rejection
    if (any(lessThan(historyTexCoord, vec2(0.0))) || any(greaterThan(historyTexCoord, vec2(1.0)))){
        return Input;
    }

    // disocclusion rejection here
    float previousDepth = linearizeDepth(texelFetch(swrtHDepth, ivec2(historyTexCoord), 0).r, NearPlane, FarPlane);
    float depthDifference = abs(previousDepth - currentDepth);
    //float threshold = 0.3 * currentDepth;
    float threshold = 0.5 * currentDepth;
    if (depthDifference > threshold) return Input; //return vec4(vec3(1.0,0.0,0.0), 1.0);

    // accumulate
    //float blendFactor = 0.9;
    //clamp(temporalAccumulationBlendFactor, 0.0, 0.9)
    indirectChannels nIC; nIC = Input;
    float factor = clamp(temporalAccumulationBlendFactor, 0.0, 0.9);
    nIC.indirect = accumulate(Input.indirect.rgb, hIndirect, historyTexCoord, factor);
    nIC.emission = accumulate(Input.emission.rgb, hEmission, historyTexCoord, factor);
    if (roughness > 0.4){
        nIC.idirectSpecular = accumulate(Input.idirectSpecular.rgb, hIndirectSpecular, historyTexCoord, factor);
        nIC.emissionSpecular = accumulate(Input.emissionSpecular.rgb, hEmissionSpecular, historyTexCoord, factor);
    }

    return nIC;
}


void main() {
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = ivec2(screenSize); // could do imagesize but this is quicker
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;
    
    if (drawSDFSCENE){ // SDF SCENE VIEW
        //vec2 uv = (pixelCoords - 0.5) * 2.0;
        // stop using inverse on the gpu here for the glm one
        vec3 rayDir = rayDirfromCam(inverse(u_ProjectionMatrix), inverse(u_ViewMatrix), pixelCoords, size);

        hitresult hr = raymarchScene(cameraPosition, rayDir, 128, mindist, 128);
        //material nMaterial = getMaterial(hr.materialIndex, hr.uv, 0);

        //FragColor.rgb = hr.normal;
        //FragColor.rgb = textureLod(sampler2D(lSDFS[hr.materialIndex].texture_diffuse_Handle), hr.uv, 0).rgb;
        //imageStore(odirect, pixelCoords, vec4(vec3(textureLod(lSDFS[hr.materialIndex].texture_diffuse_Handle, hr.uv, 0).rgb), 1.0)); // working
        return;
    }
    float gdepth = texelFetch(depthMap, pixelCoords, 0).r;
    if (gdepth >= 0.99999) return;

    vec3 gp = texelFetch(gPosition, pixelCoords, 0).xyz;
    vec3 gnrm = normalize(texelFetch(gNormal, pixelCoords, 0).xyz);
    vec3 galbedo = texelFetch(gAlbedoSpec, pixelCoords, 0).xyz;
    //vec3 gemission = texture(gEmission, pixelCoords).xyz;
    vec3 garm = texelFetch(gSpecular, pixelCoords, 0).xyz;

    float noise = blueNoise(pixelCoords);

    float ao = 1.0;
    vec3 origin = gp + gnrm * originEplison;
    if (!discardThresholdFloat(noise, ao_noiseThreshold) && aosEnabled) ao = calcAO(origin, gnrm);
    vec3 shadow = vec3(0.0f);
    shadow = direcLight(garm, gnrm, gp, doContactShadows, pixelCoords).rgb; // true false
    //shadow += directAmbient;
    shadow *=  ao;
    shadow = clamp(shadow, 0.0, 1.0);

    indirectChannels nIC;
    if (!discardThresholdFloat(noise, i_noiseThreshold) ) nIC = indirectAndEmissionMarch(garm, gnrm, origin, gnrm, i_maxdist, mindist, i_steps, i_samples, pixelCoords);
    if (!discardThresholdFloat(noise, r_noiseThreshold) ) nIC.specular = reflection(garm, gnrm, origin, reflect(normalize(gp - cameraPosition),  gnrm), r_maxdist, mindist, r_steps, r_bounces, r_samples, r_doSSR,pixelCoords);

    nIC.specular = clamp(nIC.specular, 0.0, 1.0);

    //imageStore(odirect, pixelCoords, vec4(vec3(shadow), 1.0));
    imageStore(ospecular, pixelCoords, vec4(vec3(nIC.specular), 1.0));

    vec3 null = vec3(1.0f, 0.0f, 0.0f);
    nIC.idirectSpecular.rgb = nIC.specular; // nIC.specular null
    nIC.emissionSpecular.rgb = null;

    // temporal accumulation here
    highp vec2 velocity = texelFetch(gVelocity, pixelCoords, 0).rg;

    bool split = true;
    if (pixelCoords.x > screenSize.x / 2 && doDenoiseSplitDBGView) split = false;

    if (doTemporalAccumulation && split && false){ // force off
        float d = linearizeDepth(texelFetch(depthMap, pixelCoords, 0).r, NearPlane, FarPlane);
        highp vec2 historyTexCoord = pixelCoords - velocity;

        indirectChannels nNIC =  temporalAccumulate(nIC, historyTexCoord, d, garm.g);

        imageStore(oindirect, pixelCoords, nNIC.indirect);
        imageStore(oemission, pixelCoords, nNIC.emission);
        imageStore(oindirectSpecular, pixelCoords, nNIC.idirectSpecular);
        imageStore(oemissionSpecular, pixelCoords, nNIC.emissionSpecular);

        return;
    }

    imageStore(oindirect, pixelCoords, nIC.indirect);
    imageStore(oemission, pixelCoords, nIC.emission);
    imageStore(oindirectSpecular, pixelCoords, nIC.idirectSpecular);
    imageStore(oemissionSpecular, pixelCoords, nIC.emissionSpecular);
    
    /*
    imageStore(oindirect, pixelCoords, vec4(0.5, 0.0, 0.0, 1.0)); // working
    imageStore(ospecular, pixelCoords, vec4(1.0, 0.0, 0.0, 1.0)); // working
    imageStore(oemission, pixelCoords, vec4(1.0, 0.5, 0.0, 1.0)); // working
    imageStore(oindirectSpecular, pixelCoords, vec4(1.0, 1.0, 0.0, 1.0)); // working
    imageStore(oemissionSpecular, pixelCoords, vec4(1.0, 1.0, 0.5, 1.0)); // working
    imageStore(odirect, pixelCoords, vec4(1.0, 1.0, 1.0, 1.0)); // working
    */
}